<?php
/**@var $this \Zend\View\Renderer\PhpRenderer */
/**@var $form \User\Form\SignupForm */
$this->form();
$form->prepare();

?>
<div class="row">
    <div class="span6">
        <h2>Belum tergabung dengan Kateglo?</h2>
        <?php
        echo $this->form()->openTag($form);
        ?>
        <fieldset>
            <?php foreach($form->getElements() as $element) : ?>
            <div class="control-group <?php if($this->formElementErrors($element)) echo "error" ?>">
            <?= $this->formRow($form->get('username'))?>
            <?=$this->formRow($form->get('email'))?>
            <?=$this->formRow($form->get('password'))?>
            <?=$this->formRow($form->get('password-retype'))?>
            </div>
            <?php endforeach; ?>
            <button class="btn btn-large btn-primary btn-signup" type="submit">Daftar sekarang!</button>
        </fieldset>
        <?php
        echo $this->form()->closeTag();
        ?>
    </div>
</div>