<div class="row">
    <div class="span6">
        <h2>Belum tergabung dengan Kateglo?</h2>
        <?php
        $this->form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <fieldset>
            <?= $this->formRow($this->form->get('username'))?>
            <?=$this->formRow($this->form->get('email'))?>
            <?=$this->formRow($this->form->get('password'))?>
            <?=$this->formRow($this->form->get('password-retype'))?>
            <?=$this->formButton()->render($this->form->get('submit'), 'Daftar Sekarang!')?>
        </fieldset>
        <?php
        echo $this->form()->closeTag();
        ?>
    </div>
</div>