<?php
/**@var $this \Zend\View\Renderer\PhpRenderer */
/**@var $form \Zend\Form\Form */
/**@var $formElementErrors \Zend\Form\View\Helper\FormElementErrors */
$formElementErrors = $this->formElementErrors();
$formElementErrors->setMessageOpenFormat('')->setMessageSeparatorString('')->setMessageCloseString('');
$this->form->prepare();
?>
<div class="row">
    <div class="span6">
        <h2>Masuk</h2>
        <?= $this->form()->openTag($form); ?>
        <fieldset>
            <?php if(isset($this->messages)) :?>
            <div class="control-group error">
                <div class="controls">
                    <span class="help-inline"><?=$this->messages ?></span>
                </div>
            </div>
            <?php endif; ?>
            <?php foreach ($form->getElements() as $element) : ?>
            <div class="control-group<?=$this->formElementErrors($element) ? ' error' : '' ?>">
                <div class="controls">
                    <?=$this->formElement($element);?>
                    <?php if ($this->formElementErrors($element)): ?>
                    <span class="help-inline"><?=$this->formElementErrors($element) ?></span>
                    <?php endif; ?>
                </div>
            </div>
            <?php endforeach; ?>
            <button class="btn btn-large btn-primary btn-signup" type="submit">Masuk</button>
        </fieldset>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>