<div class="row">
    <div class="span12 center">
        <div id="home-container">
            <h1 class="logo">Kateglo</h1>

            <form class="form-search" action="entri.html">
                <div class="input-append">
                    <input type="search" class="input-xxlarge search-query"
                           placeholder="Masukkan kata, peribahasa atau singkatan...">
                    <button type="submit" class="btn">Telusuri</button>
                </div>
            </form>
        </div>
    </div>
</div>